config/routes.rb
Rails.application.routes.draw do


  namespace :users do

    resources :products
# お気に入り商品ページ
    get 'user_likes', to: 'products#user_likes', as: :user_likes
    # お気に入り登録
    get 'user_like/:id', to: 'products#user_like', as: :user_like

# ユーザーページ（トップ）
    # プロフィール
    get 'profile/:id', to: 'users#show', as: :users_profile
    # プロフィール更新
    get 'profile/:id/edit', to: 'users#edit', as: :edit_profile
    patch 'profile/:id', to: 'users#update'

# ログイン機構
    # ユーザー登録
    get 'sign_up', to: 'users#sign_up'
    post 'sign_up', to: 'users#sign_up_process'
    # ログイン
    get 'sign_in', to: 'users#sign_in'
    post 'sign_in', to: 'users#sign_in_process'
    # ログアウト
    delete 'sign_out', to: 'users#sign_out'
  end


# 商品一覧（トップ）
  root 'markets/markets#index'

# 一覧ページ
  namespace :markets do
    # 以下、検索と詳細の順番を逆にすると、検索時にshowアクションが読まれる
    # 商品検索
    get 'search', to: 'markets#search', as: :search
    # 商品詳細
    get '/:id', to: 'markets#show', as: :product_show

    get '/:id/purchase', to: 'markets#purchase', as: :purchase
    # 購入する
    post '/:id/buy', to: 'markets#buy', as: :buy
  end

end

app/models/user.rb
class User < ApplicationRecord
	# include Paperclip::Glue

	has_many :products
	has_many :user_likes

	# passwordとpassword_confirmationカラムが存在しなくても、存在するかのように振る舞う
	# gem 'bcrypt' が必要
	has_secure_password validations: true
	# 明示的に、presenceと最低文字数を設定（password）
	validates :password, presence: true, length: { minimum: 4 }
	validates :name, presence: true

	# emailの形式制限
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true

	# サムネイルの設定（paperclip)
	# 参考：https://qiita.com/chamao/items/181451a0f6d875a3c407
	has_attached_file :image,
                      styles: { medium: "300x300>", thumb: "100x100>" },
                      path: "#{Rails.root}/app/assets/images/:filename"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController

	def index
		# binding.pry
		# @user = User.find(params[:id])
		# @products = User.find(params[:id]).products.all
		@products = Product.where(user_id: current_user)
	end

	# def show
	# 	@product = Product.find(params[:product_id])
	# end

	def show
		@product = Product.find_by(id: params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		product = Product.new(product_params)
		if product.save
			redirect_to root_url, flash: { success: '商品を登録しました。' }
		else
			flash[:danger] = '商品登録に失敗しました。'
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		@product.update(product_params)
		flash[:suceess] = "商品を編集しました。"
		redirect_to users_product_url
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		flash[:success] = '商品を削除しました。'
		redirect_to users_products_url
	end

	def user_like
		if UserLike.exists?(user_id: current_user.id, product_id: params[:id])
			UserLike.find_by(user_id: current_user.id, product_id: params[:id]).destroy
			redirect_back(fallback_location: root_path)
		else
			UserLike.create(user_id: current_user.id, product_id: params[:id])
			redirect_back(fallback_location: root_path)
		end
	end

	def user_likes
		product_ids = User.find(current_user.id).user_likes.pluck(:product_id)
		@products = product_ids.map { |id| Product.find(id) }		
	end

	private

	def product_params
		params.require(:product).permit(:name, :description, :price, :category_id, :user_id, :image1, :image2, :image3)
	end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

	# ログイン時に、ログインユーザーを特定する必要あるので、set_userでユーザー特定をまず行う
	before_action :set_user, only: :sign_in_process

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(current_user.id)
	end

	def update
		if current_user.update(user_params)
			flash[:success] = '更新しました。'
			redirect_to users_users_profile_url
		else
			render 'edit'
		end
	end

	def sign_up
		@user = User.new
		render layout: '2nd_application'
	end

	def sign_up_process
		user = User.new(user_params)
		if user.save
			flash[:success] = '登録しました。'
			user_sign_in(user)
			redirect_to root_path
		else
			flash[:danger] = '登録に失敗しました。やり直してください。'
			flash[:warning] = user.errors.full_messages[0]
			redirect_to users_sign_up_url(user)
		end
	end

	def sign_in
		@user = User.new
		render layout: '2nd_application'
	end

	def sign_in_process
		if user_params[:email].present? && user_params[:password].present?
			if @user.authenticate(user_params[:password]) && @user.email == user_params[:email]
				user_sign_in(@user)
				flash[:success] = 'ログインしました。'
				redirect_to root_path
			else
				flash[:danger] = 'ログインに失敗しました'
				render 'sign_in'
			end
		else
			flash[:danger] = "必要項目を入力してください"
			redirect_to users_sign_in_path
		end
	end

	def sign_out
		user_sign_out
		flash[:success] = 'ログアウトしました。'
		redirect_to users_sign_in_url
	end

	# def authorize
	# end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :image)
		end

		def set_user
			@user = User.find_by!(email: user_params[:email]) if user_params[:email].present?
		end


end

app/helpers/users_helper.rb
module UsersHelper

	def user_sign_in(user)
		session[:user_id] = user.id
		current_user
	end

	def user_sign_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		if @current_user.nil?
			@current_user = User.find(session[:user_id]) if session[:user_id]
		else
			@current_user
		end
	end

	def user_signed_in?
		current_user.present?
	end
end

app/views/users/users/edit.html.erb
<% if current_user.errors.any? %>
	<div class="alert alert-danger">
		<ul>
			<% current_user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end -%>
		</ul>
	</div>
<% end -%>

<div class="profile_edit">
	<div class="profile_edit-form">
		<div>プロフィールを変更する</div>
		<%= form_for current_user, url: users_users_profile_path, method: :patch do |f| %>
			<%= f.text_field :email, placeholder: 'email' %>
			<%= f.text_field :password, placeholder: 'password' %>
			<%= f.text_field :password_confirmation, placeholder: 'password_confirmation' %>
			<%= f.text_area :profile, placeholder: 'profile' %>
			<%= f.file_field :image %>
			<%= f.submit '更新する' %>
		<% end -%>
	</div>
</div>

app/views/users/users/show.html.erb
<div class="profile">
	<h3>わたくしのプロフィール</h3>
	<%= image_tag @user.image_file_name if @user.image_file_name.present? %>
	<ul>
		<li>ニックネーム: <%= @user.name %></li>
		<li>出品数: <%= @user.products.size %></li>
		<li>コメント: <%= @user.profile %></li>
	</ul>
</div>

app/views/users/users/sign_in.html.erb
<div class="sign_in">
	<div class="sign_in-form">
		<div>サインインする</div>
		<%= form_for @user, url: users_sign_in_path, method: :post do |f| %>
			<%= f.text_field :email, placeholder: 'email' %>
			<%= f.text_field :password, placeholder: 'password' %>
			<%= f.submit %>
		<% end -%>
		<%= link_to 'ユーザー登録する', users_sign_up_path %>
	</div>
</div>

app/views/users/users/sign_up.html.erb
<div class="sign_up">
	<div class="sign_up-form">
		<div>ユーザー登録する</div>
		<%= form_for @user, url: users_sign_up_path, method: :post do |f| %>
			<%= f.text_field :name, placeholder: 'name' %>
			<%= f.text_field :email, placeholder: 'email' %>
			<%= f.text_field :password, placeholder: 'password' %>
			<%= f.text_field :password_confirmation, placeholder: 'password confirmation' %>
			<%= f.submit %>
		<% end -%>
	</div>
</div>