config/routes.rb
Rails.application.routes.draw do


  namespace :users do

    resources :products
# お気に入り商品ページ
    get 'user_likes', to: 'products#user_likes', as: :user_likes
    # お気に入り登録
    get 'user_like/:id', to: 'products#user_like', as: :user_like

# ユーザーページ（トップ）
    # プロフィール
    get 'profile/:id', to: 'users#show', as: :users_profile
    # プロフィール更新
    get 'profile/:id/edit', to: 'users#edit', as: :edit_profile
    patch 'profile/:id', to: 'users#update'

# ログイン機構
    # ユーザー登録
    get 'sign_up', to: 'users#sign_up'
    post 'sign_up', to: 'users#sign_up_process'
    # ログイン
    get 'sign_in', to: 'users#sign_in'
    post 'sign_in', to: 'users#sign_in_process'
    # ログアウト
    delete 'sign_out', to: 'users#sign_out'
  end


# 商品一覧（トップ）
  root 'markets/markets#index'

# 一覧ページ
  namespace :markets do
    # 以下、検索と詳細の順番を逆にすると、検索時にshowアクションが読まれる
    # 商品検索
    get 'search', to: 'markets#search', as: :search
    # 商品詳細
    get '/:id', to: 'markets#show', as: :product_show

    get '/:id/purchase', to: 'markets#purchase', as: :purchase
    # 購入する
    post '/:id/buy', to: 'markets#buy', as: :buy
  end

end

app/controllers/markets/markets_controller.rb
class Markets::MarketsController < ApplicationController
	layout 'layouts/2nd_application'
  	def index
  		@products = Product.all.order(updated_at: :desc)
  	end

	def show
		@product = Product.find(params[:id])
	end

	def search
		@products = Product.all

# scopeとは、SQL文をメソッド化するもの
# -------------------------------------------
	# キーワード検索
		@products = @products.name_like(params[:key_word]) if params[:key_word].present?
	# カテゴリー検索
		@products = @products.by_category(params[:category_id]) if params[:category_id].present?
# -------------------------------------------
	# 価格検索
		# 以下は値のどちらかが空の場合にエラーを返す
		# if params[:price_low].present? && params[:price_high].present?
		# 	@products = @products.price_range(params[:price_low]..params[:price_high])
		# elsif params[:price_low].present? || params[:price_high].present?
		# 	flash.now[:warning] = '価格検索のどちらかの値が空欄です'
		# end

		# 価格検索もうひとつの書き方（scope使用）- 空の要素に Float::INFINITY使うと、Infinityになる（この場合は終わりの値が空の時、プラス値の無限数）
		# 最初の値が空""の場合、to_iで数値化することで、0に置き換わるのでどちらの値が空欄でも検索可能（0..Infinity)
		@products = @products.price_range(params[:price_low].to_i..(params[:price_high].blank? ? Float::INFINITY : params[:price_high].to_i))
# -------------------------------------------
	# 並び替え
		@products = @products.order(price: :desc) if params[:sort] === "high"
		@products = @products.order(price: :asc) if params[:sort] === "low"
		@products = @products.order(updated_at: :asc) if params[:sort] === "old"
		@products = @products.order(updated_at: :desc) if params[:sort] === "new"

		# 商品一覧で検索結果を表示
		render 'markets/markets/index' 
		# render とredirect_to の違い = renderはアクション内で呼ぶviewを指定。redirect_toは、HTTPリクエストをサーバーに送り、そこから返る結果をhtmlに表示。
	end


	def purchase
		@product = Product.find(params[:id])
	end

	def buy
		# enumを使う場合
		# Product.find(params[:id]).sold!
		Product.find(params[:id]).update(status: 1)
		redirect_to root_path, flash: { success: '商品を購入しました' }
	end

end


# カテゴリーで一度抽出した要素から、
# キーワードで抽出した要素を検索する
# @products.where(category_id: 1)

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/markets/index.html.erb
<div class="main_left_continer">
	<% if @products.present? %>
		<% @products.each do |p| %>
			<div class="product_info">
				<% if p.status === true %>
					<div class="sold">SOLD</div>
				<% end -%>
				<%= link_to image_tag(image_url_1(p)), (p.user_id === current_user.id) ? users_product_path(p) : markets_product_show_path(p) %>
				
				<p style="font-size: 15px; color: gray"><%= p.category.name %></p>
				<p>商品名: <%= p.name %></p>
				<p>価格: <%= p.price %></p>
				<% if user_signed_in? %>
					<%= link_to users_user_like_path(p) do %>
						<i class="fa fa-star fa-3x <%= p.like_by?(current_user) ? "active" : "" %>"></i>
					<% end -%>
				<% end -%>
			</div>
		<% end -%>
	<% else %>
		<p>商品はありません</p>
	<% end -%>
</div>

app/views/markets/markets/purchase.html.erb
<div class="main_left_continer">
	<div class="product_information">
		<h1><%= @product.name %></h1>

<!-- 		<img src="<%= @product.image1 %>" width='550'>
		<img src="<%= @product.image2 %>" width='550'>
		<img src="<%= @product.image3 %>" width='550'> -->
		
		<!-- 未登録の画像にダミーを利用する場合 -->
		<img src="<%= image_url_1(@product) %>" width='550'>
		<img src="<%= image_url_2(@product) %>" width='550'>
		<img src="<%= image_url_3(@product) %>" width='550'>

		<p>カテゴリー: <%= @product.category.name %></p>
		<h3>¥<%= @product.price.to_s(:delimited) %></h3>
		<div class="buy_btn_container"><%= link_to '購入を確定する', markets_buy_path(@product), method: :post, class: 'buy_btn' %></div>
		<p><%= @product.description %></p>
	</div>
</div>

app/views/markets/markets/show.html.erb
<div class="main_left_continer">
	<div class="product_information">
		<h1><%= @product.name %></h1>

<!-- 		<img src="<%= @product.image1 %>" width='550'>
		<img src="<%= @product.image2 %>" width='550'>
		<img src="<%= @product.image3 %>" width='550'> -->
		
		<!-- 未登録の画像にダミーを利用する場合 -->
		<img src="<%= image_url_1(@product) %>">
		<img src="<%= image_url_2(@product) %>">
		<img src="<%= image_url_3(@product) %>">

		<p>カテゴリー: <%= @product.category.name %></p>
		<h3>¥<%= @product.price.to_s(:delimited) %></h3>
		<% if @product.status === false %>
			<div class="buy_btn_container"><%= link_to '購入する', markets_purchase_path(@product), class: 'buy_btn' %></div>
		<% end -%>
		<p><%= @product.description %></p>
	</div>
</div>