config/routes.rb
Rails.application.routes.draw do


  namespace :users do

    resources :products
# お気に入り商品ページ
    get 'user_likes', to: 'products#user_likes', as: :user_likes
    # お気に入り登録
    get 'user_like/:id', to: 'products#user_like', as: :user_like

# ユーザーページ（トップ）
    # プロフィール
    get 'profile/:id', to: 'users#show', as: :users_profile
    # プロフィール更新
    get 'profile/:id/edit', to: 'users#edit', as: :edit_profile
    patch 'profile/:id', to: 'users#update'

# ログイン機構
    # ユーザー登録
    get 'sign_up', to: 'users#sign_up'
    post 'sign_up', to: 'users#sign_up_process'
    # ログイン
    get 'sign_in', to: 'users#sign_in'
    post 'sign_in', to: 'users#sign_in_process'
    # ログアウト
    delete 'sign_out', to: 'users#sign_out'
  end


# 商品一覧（トップ）
  root 'markets/markets#index'

# 一覧ページ
  namespace :markets do
    # 以下、検索と詳細の順番を逆にすると、検索時にshowアクションが読まれる
    # 商品検索
    get 'search', to: 'markets#search', as: :search
    # 商品詳細
    get '/:id', to: 'markets#show', as: :product_show

    get '/:id/purchase', to: 'markets#purchase', as: :purchase
    # 購入する
    post '/:id/buy', to: 'markets#buy', as: :buy
  end

end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :user_likes

	# サムネイルの設定（paperclip)
	# 参考：https://qiita.com/chamao/items/181451a0f6d875a3c407
	# has_attached_file :image1,
 #                      styles: { medium: "300x300>", thumb: "100x100>" },
 #                      path: "#{Rails.root}/app/assets/images/products/:filename"
 #  	validates_attachment_content_type :image1, content_type: /\Aimage\/.*\z/


 	# carrierwave
  	mount_uploader :image1, ImageUploader
  	mount_uploader :image2, ImageUploader
  	mount_uploader :image3, ImageUploader


# 名前検索
  	scope :name_like, -> key_word { where('name like ?', "%#{key_word}%")}
# カテゴリー検索
	# scope :by_category, -> category_id { joins(:category).where(category_id: category_id)}
	scope :by_category, -> category_id { where(category_id: category_id)}
# 価格検索（scope使う場合）
	scope :price_range, ->(range) { where(price: range) }


# ----------------------------------------------------
# statusカラムの値の触り方（初期値を入れない場合）
	# 出品中か売り切れかの判断
	# enum status: {
	# 	on_sale:  0,
	# 	sold: 1
	# }
	# # 商品登録時に statusを'0'にする
	# before_create { self.status = Product.statuses[:on_sale] }
# ----------------------------------------------------


  	def like_by?(user)
  		self.user_likes.exists?(user_id: user.id)
  	end

end


# :image1, :image2, :image3,



# joinsはモデルにしか使えない　一度変数に格納すると、使えないので
# まずモデルをjoinsさせる
# Product.joins(:category).where(@products.pluck(:id))

app/models/user.rb
class User < ApplicationRecord
	# include Paperclip::Glue

	has_many :products
	has_many :user_likes

	# passwordとpassword_confirmationカラムが存在しなくても、存在するかのように振る舞う
	# gem 'bcrypt' が必要
	has_secure_password validations: true
	# 明示的に、presenceと最低文字数を設定（password）
	validates :password, presence: true, length: { minimum: 4 }
	validates :name, presence: true

	# emailの形式制限
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true

	# サムネイルの設定（paperclip)
	# 参考：https://qiita.com/chamao/items/181451a0f6d875a3c407
	has_attached_file :image,
                      styles: { medium: "300x300>", thumb: "100x100>" },
                      path: "#{Rails.root}/app/assets/images/:filename"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController

	def index
		# binding.pry
		# @user = User.find(params[:id])
		# @products = User.find(params[:id]).products.all
		@products = Product.where(user_id: current_user)
	end

	# def show
	# 	@product = Product.find(params[:product_id])
	# end

	def show
		@product = Product.find_by(id: params[:id])
	end

	def new
		@product = Product.new
	end

	def create
		product = Product.new(product_params)
		if product.save
			redirect_to root_url, flash: { success: '商品を登録しました。' }
		else
			flash[:danger] = '商品登録に失敗しました。'
			render 'new'
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		@product.update(product_params)
		flash[:suceess] = "商品を編集しました。"
		redirect_to users_product_url
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		flash[:success] = '商品を削除しました。'
		redirect_to users_products_url
	end

	def user_like
		if UserLike.exists?(user_id: current_user.id, product_id: params[:id])
			UserLike.find_by(user_id: current_user.id, product_id: params[:id]).destroy
			redirect_back(fallback_location: root_path)
		else
			UserLike.create(user_id: current_user.id, product_id: params[:id])
			redirect_back(fallback_location: root_path)
		end
	end

	def user_likes
		product_ids = User.find(current_user.id).user_likes.pluck(:product_id)
		@products = product_ids.map { |id| Product.find(id) }		
	end

	private

	def product_params
		params.require(:product).permit(:name, :description, :price, :category_id, :user_id, :image1, :image2, :image3)
	end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

	# ログイン時に、ログインユーザーを特定する必要あるので、set_userでユーザー特定をまず行う
	before_action :set_user, only: :sign_in_process

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(current_user.id)
	end

	def update
		if current_user.update(user_params)
			flash[:success] = '更新しました。'
			redirect_to users_users_profile_url
		else
			render 'edit'
		end
	end

	def sign_up
		@user = User.new
		render layout: '2nd_application'
	end

	def sign_up_process
		user = User.new(user_params)
		if user.save
			flash[:success] = '登録しました。'
			user_sign_in(user)
			redirect_to root_path
		else
			flash[:danger] = '登録に失敗しました。やり直してください。'
			flash[:warning] = user.errors.full_messages[0]
			redirect_to users_sign_up_url(user)
		end
	end

	def sign_in
		@user = User.new
		render layout: '2nd_application'
	end

	def sign_in_process
		if user_params[:email].present? && user_params[:password].present?
			if @user.authenticate(user_params[:password]) && @user.email == user_params[:email]
				user_sign_in(@user)
				flash[:success] = 'ログインしました。'
				redirect_to root_path
			else
				flash[:danger] = 'ログインに失敗しました'
				render 'sign_in'
			end
		else
			flash[:danger] = "必要項目を入力してください"
			redirect_to users_sign_in_path
		end
	end

	def sign_out
		user_sign_out
		flash[:success] = 'ログアウトしました。'
		redirect_to users_sign_in_url
	end

	# def authorize
	# end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :image)
		end

		def set_user
			@user = User.find_by!(email: user_params[:email]) if user_params[:email].present?
		end


end

app/helpers/products_helper.rb
module ProductsHelper

# ダミー画像設定
# 一括で小さいサイズにリサイズして、大きく見せたい場所ではサイズ指定して引き延ばす
	def image_url_1(product)
		if product.image1.blank?
			"https://dummyimage.com/200x200/000/fff"
		else
			product.image1.thum50.url
		end
	end
	def image_url_2(product)
		if product.image2.blank?
			"https://dummyimage.com/200x200/000/fff"
		else
			product.image2.thum50.url
		end
	end
	def image_url_3(product)
		if product.image3.blank?
			"https://dummyimage.com/200x200/000/fff"
		else
			product.image3.thum50.url
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper

	def user_sign_in(user)
		session[:user_id] = user.id
		current_user
	end

	def user_sign_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		if @current_user.nil?
			@current_user = User.find(session[:user_id]) if session[:user_id]
		else
			@current_user
		end
	end

	def user_signed_in?
		current_user.present?
	end
end

app/views/users/products/edit.html.erb
<div class="profile_edit">
	<div class="profile_edit-form">
		<div>出品商品を編集する</div>
		<%= form_for @product, url: users_product_path, method: :patch do |f| %>
			<%= f.text_field :name, placeholder: '商品名' %>
			<%= f.text_field :price, placeholder: '価格' %>
			<%= f.text_field :description, placeholder: '商品説明' %>
			<%= f.collection_select :category_id, Category.all, :id, :name %>
			<br>
			<%= f.file_field :image1 %>
			<%= f.file_field :image2 %>
			<%= f.file_field :image3 %>
			<%= f.hidden_field :user_id, value: current_user.id %>
			<br>
			<%= f.submit '登録する' %>
		<% end -%>
	</div>
</div>

app/views/users/products/index.html.erb
<div class="main_left_continer">
	<h3>あなたの出品商品一覧</h3>
	<% if @products.present? %>
		<% @products.each do |p| %>
			<div class="product_info">
				<%= link_to image_tag(image_url_1(p)), users_product_path(p) %>

				<p style="font-size: 15px; color: gray"><%= p.category.name %></p>
				<p>商品名: <%= p.name %></p>
				<p>価格: <%= p.price %></p>
			</div>
		<% end -%>
	<% else %>
		<p>出品商品はありません</p>
	<% end -%>
</div>

app/views/users/products/new.html.erb
<h3>新たな商品を登録する</h3>
<!-- ここ、@productでなぜダメか検証 -->
<%= form_for Product.new, url: users_products_path, method: :post do |f| %>
	<%= f.text_field :name, placeholder: '商品名' %>
	<%= f.text_field :price, placeholder: '価格' %>
	<%= f.text_field :description, placeholder: '商品説明' %>
	<%= f.collection_select :category_id, Category.all, :id, :name %>
	<br>
	<%= f.file_field :image1 %>
	<%= f.file_field :image2 %>
	<%= f.file_field :image3 %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<br>
	<%= f.submit '登録する' %>
<% end -%>

app/views/users/products/show.html.erb
<div class="main_left_continer">
	<div class="product_information">
		<h1><%= @product.name %></h1>

<!-- 		<img src="<%= @product.image1 %>" width='550'>
		<img src="<%= @product.image2 %>" width='550'>
		<img src="<%= @product.image3 %>" width='550'> -->

		<!-- 未登録の画像にダミーを利用する場合 -->
		<img src="<%= image_url_1(@product) %>" width='550' height='550'>
		<img src="<%= image_url_2(@product) %>" width='550' height='550'>
		<img src="<%= image_url_3(@product) %>" width='550' height='550'>

		<p>カテゴリー: <%= @product.category.name %></p>
		<h3>¥<%= @product.price.to_s(:delimited) %></h3>
		<p><%= @product.description %></p>
		<div class="buy_btn_container"><%= link_to '商品を編集', edit_users_product_path(@product), class: 'buy_btn' %></div>
		<%= link_to 'この商品を削除する', users_product_path(@product), method: :delete, class: 'product_delete' %>
	</div>
</div>

app/views/users/products/user_likes.html.erb
<div class="main_left_continer">
	<h3>お気に入り商品</h3>
	<% if @products.present? %>
		<% @products.each do |p| %>
			<div class="product_info">
				<% if p.status === true %>
					<div class="sold">SOLD</div>
				<% end -%>
				<%= link_to image_tag(image_url_1(p)), (p.user_id === current_user.id) ? users_product_path(p) : markets_product_show_path(p) %>

				<p style="font-size: 15px; color: gray"><%= p.category.name %></p>
				<p>商品名: <%= p.name %></p>
				<p>価格: <%= p.price %></p>
				<%= link_to users_user_like_path(p) do %>
					<i class="fa fa-star fa-3x <%= p.like_by?(current_user) ? "active" : "" %>"></i>
				<% end -%>
			</div>
		<% end -%>
	<% else %>
		<p>出品商品はありません</p>
	<% end -%>
</div>