config/routes.rb
Rails.application.routes.draw do


  namespace :users do

    resources :products
# お気に入り商品ページ
    get 'user_likes', to: 'products#user_likes', as: :user_likes
    # お気に入り登録
    get 'user_like/:id', to: 'products#user_like', as: :user_like

# ユーザーページ（トップ）
    # プロフィール
    get 'profile/:id', to: 'users#show', as: :users_profile
    # プロフィール更新
    get 'profile/:id/edit', to: 'users#edit', as: :edit_profile
    patch 'profile/:id', to: 'users#update'

# ログイン機構
    # ユーザー登録
    get 'sign_up', to: 'users#sign_up'
    post 'sign_up', to: 'users#sign_up_process'
    # ログイン
    get 'sign_in', to: 'users#sign_in'
    post 'sign_in', to: 'users#sign_in_process'
    # ログアウト
    delete 'sign_out', to: 'users#sign_out'
  end


# 商品一覧（トップ）
  root 'markets/markets#index'

# 一覧ページ
  namespace :markets do
    # 以下、検索と詳細の順番を逆にすると、検索時にshowアクションが読まれる
    # 商品検索
    get 'search', to: 'markets#search', as: :search
    # 商品詳細
    get '/:id', to: 'markets#show', as: :product_show

    get '/:id/purchase', to: 'markets#purchase', as: :purchase
    # 購入する
    post '/:id/buy', to: 'markets#buy', as: :buy
  end

end

app/views/layouts/2nd_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freemarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="main_body">
      <div class="main_container">
          <div class="main_left">
            <% flash.each do |type, message| %>
              <div class="alert alert-<%= type %>"><%= message %></div>
            <% end -%>
            
            <%= yield %>
          </div>
          <div class="main_right">
            <%= render partial: 'layouts/side_menu2' %>
          </div>
      </div>
    </div>
    <footer></footer>
  </body>
</html>

app/views/layouts/_header.html.erb
<header>
	<div class="header_content">
		<div class="hello_user">
			<% if user_signed_in? %>
			    <p>ようこそ、id: <%= current_user.id %> の <%= current_user.name %>さん</p>
			<% end -%>
		</div>
		<%= link_to 'Free Marketへ', root_path, class: 'title' %>
	    <% if user_signed_in? %>
		    <div class="my_page_container">
			    <%= link_to users_users_profile_path(current_user) do %>
			    	<i class="fa fa-address-card fa-2x my_page"></i>
				    <p>マイページ</p>
			    <% end -%>
		    </div>
	    <% end -%>
	    <%= link_to '出品する', new_users_product_path, class: 'button' %>
	      <!-- 検索フォーム -->
	    <form class="search">
	        <!-- name="word"となっているため、nameという名前でキーワードの値が送られる -->
	        <input class="search_window" type="text" placeholder="キーワードから検索" name="word" value="">
	    </form>


  	</div>
  	<div style="clear: both;"></div>
</header>

app/views/layouts/_side_menu.html.erb
<div class="side_container">
	<h1>マイページ</h1>
	<p><%= link_to '出品する', new_users_product_path, class: 'side_btn' %></p>
	<p><%= link_to '出品中の商品', users_products_path(current_user), class: 'side_btn' %></p>
	<p><%= link_to 'お気に入りの商品', users_user_likes_path(current_user), class: 'side_btn' %></p>
	<p><%= link_to 'プロフィールを更新', users_edit_profile_path(current_user), class: 'side_btn' %></p>
	<p>
		<% if user_signed_in? %>
		    <%= link_to 'ログアウト', users_sign_out_path(current_user), method: :delete, class: 'side_btn' %>
		<% end -%>
	</p>
</div>

app/views/layouts/_side_menu2.html.erb
<div class="side_container">
	<h1>詳細検索</h1>

	<%= form_tag(markets_search_path, method: :get)do %>
		<p>
		<%= label_tag :key_word, 'キーワード追加' %>
		<%= text_field_tag :key_word, params[:key_word], placeholder: '[例] 値下げ' %>
		</p>
		<p>
		<%= label_tag :category_id, 'カテゴリー選択' %>
		<!-- pluck()の書き方 - 表示は カテゴリーname なので、先頭に書き、idを送信に必要なので、第二引数に書く -->
		<!-- 入れ子配列の場合、最初の要素に表示名称を、次の要素に値を書く -->
		<!-- https://improve-future.com/rails-generate-option-tags-with-options_for_select.html -->
		<%= select_tag :category_id, options_for_select(Category.pluck(:name, :id), params[:category_id]), include_blank: true %>
		</p>
		<p>
			<%= label_tag :price, '価格' %>
			<%= text_field_tag :price_low, params[:price_low], placeholder: '100' %>
			<span>〜</span>
			<%= text_field_tag :price_high, params[:price_high], placeholder: '1000' %>
		</p>
		<p>
			<%= label_tag :sort, '並び替え' %>
			<%= select_tag :sort, options_for_select([['価格の高い順', :high], ['価格の安い順', :low], ['古い順', :old], ['新着順', :new]], params[:sort]), include_blank: true %>
		</p>
		<%= submit_tag '検索' %>

	<% end -%>
</div>

app/views/layouts/application.html.erb
<!-- marketsコントローラー用 -->

<!DOCTYPE html>
<html>
  <head>
    <title>Freemarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="main_body">
      <div class="main_container">
          <div class="main_left">
          	<% flash.each do |type, message| %>
          		    <div class="alert alert-<%= type %>"><%= message %></div>
          	<% end -%>
            <!-- 上記flashは、自分で文言を入力する際、
            validationの error.full_messageを表示する場合は、個別にページに表示コードを書く -->
            <%= yield %>
          </div>
          <div class="main_right">
            <%= render partial: 'layouts/side_menu' %>
          </div>
      </div>
    </div>
    <footer></footer>
  </body>
</html>